## IRIS; 사이킷런의 대표적 실습 데이터
### 붓꽃의 꽃받침, 꽃잎의 폭과 너비를 이용해서 붓꽃 품종을 예측

![title](img/iriss.png)

https://scikit-learn.org/stable/datasets/index.html  
에서 다양한 데이터셋 확인이 가능하다

### 1. 데이터 로드

In [24]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [25]:
import pandas as pd

from sklearn.datasets import load_iris

iris_dataset = load_iris()

### 2. 데이터 살펴보기

In [ ]:
type(iris_dataset)

sklearn.utils.Bunch

===========================================================  
Bunch; sklearn 에서 제공하는 데이터셋의 자료형

data: (필수) 독립 변수 ndarray 배열  
target: (필수) 종속 변수 ndarray 배열  
feature_names: (옵션) 독립 변수 이름 리스트  
target_names: (옵션) 종속 변수 이름 리스트  
DESCR: (옵션) 자료에 대한 설명
<br>
<br>
→ 일종의 딕셔너리형 구조라고 생각하면 이해하기 쉽다

===========================================================

In [4]:
print("iris_dataset의 key 값:", iris_dataset.keys())

iris_dataset의 key 값: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [7]:
# print(iris_dataset['DESCR'])
print(iris_dataset['DESCR'][:500] + "\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica


...

In [5]:
print("iris_dataset의 feature_names 값:", iris_dataset['feature_names'])
print("iris_dataset의 target_names 값:", iris_dataset['target_names'])

iris_dataset의 feature_names 값: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
iris_dataset의 target_names 값: ['setosa' 'versicolor' 'virginica']

In [6]:
# pandas 로 dataset 가져오기
print('iris dataset 의 data 값')

X_iris = pd.DataFrame(iris_dataset['data'])
X_iris.head(5) #데이터 상위 n개

iris dataset 의 data 값

     0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

### 3. Local 에서 직접 data 를 불러오도록 하자

In [30]:
iris = pd.read_csv("/content/drive/MyDrive/ML/실습 2주차/iris.csv")
iris.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

#### Data PreProcessing

##### 1. Split X and Y

In [35]:
X_iris = iris[["sepal.length","sepal.width","petal.length","petal.width"]]
y_iris = iris[["variety"]]

Column 명을 변경

In [36]:
# 컬럼명 변경 -> 'sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'
X_iris_columns = ['sepal length (cm)','sepal width (cm)','petal length (cm)','petal width (cm)'] #list
X_iris.columns = X_iris_columns
X_iris.head(5)

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [37]:
y_iris

       variety
0       Setosa
1       Setosa
2       Setosa
3       Setosa
4       Setosa
..         ...
145  Virginica
146  Virginica
147  Virginica
148  Virginica
149  Virginica

[150 rows x 1 columns]

In [38]:
y_iris['variety'].unique() #unique() : 중복되는 값없이 출력

array(['Setosa', 'Versicolor', 'Virginica'], dtype=object)

### 3. Split train set, test set

In [43]:
# 함수를 이용해서 나누기
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_iris,y_iris,test_size=0.3,random_state=0)
#train할 data,test할 data, traing할 정답,test할 정답

### 4. Machine learning modeling

In [47]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3) #n_neighbors = k

### 5. Training

In [44]:
X_train #randomly output

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
60                 5.0               2.0                3.5               1.0
116                6.5               3.0                5.5               1.8
144                6.7               3.3                5.7               2.5
119                6.0               2.2                5.0               1.5
108                6.7               2.5                5.8               1.8
..                 ...               ...                ...               ...
9                  4.9               3.1                1.5               0.1
103                6.3               2.9                5.6               1.8
67                 5.8               2.7                4.1               1.0
117                7.7               3.8                6.7               2.2
47                 4.6               3.2                1.4               0.2

[105 rows x 4 columns]

In [45]:
y_train

        variety
60   Versicolor
116   Virginica
144   Virginica
119   Virginica
108   Virginica
..          ...
9        Setosa
103   Virginica
67   Versicolor
117   Virginica
47       Setosa

[105 rows x 1 columns]

In [48]:
## knn 알고리즘 traiging
knn.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier(n_neighbors=3)

In [52]:
print(y_train.shape)
print(y_train.values.ravel().shape)
#(105,1)matrix와 (105,)matrix의 차이

(105, 1)
(105,)

In [50]:
## knn 알고리즘 traiging
knn.fit(X_train,y_train.values.ravel())

KNeighborsClassifier(n_neighbors=3)

### 6. Predict

In [57]:
import numpy as np

# 'sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)' 을 임의로 정한다
# 5.3, 2.1, 1.3, 0.2 의 수치로 정함
Our_X = np.array([[5.3,2.1,1.3,0.2]]) #다수의 데이터입력을 위해 2차배열로 생성
Our_X

array([[5.3, 2.1, 1.3, 0.2]])

In [58]:
# 임의의 데이터로 prediction
prediction = knn.predict(Our_X)
print("예측 : {}".format(prediction))

예측 : ['Setosa']

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  "X does not have valid feature names, but"

### 7. Accuracy

In [61]:
y_pred = knn.predict(X_test)
print(y_pred.shape)
print("테스트 세트에 대한 예측값:\n {}".format(y_pred))

(45,)
테스트 세트에 대한 예측값:
 ['Virginica' 'Versicolor' 'Setosa' 'Virginica' 'Setosa' 'Virginica'
 'Setosa' 'Versicolor' 'Versicolor' 'Versicolor' 'Virginica' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Setosa' 'Versicolor' 'Versicolor'
 'Setosa' 'Setosa' 'Virginica' 'Versicolor' 'Setosa' 'Setosa' 'Virginica'
 'Setosa' 'Setosa' 'Versicolor' 'Versicolor' 'Setosa' 'Virginica'
 'Versicolor' 'Setosa' 'Virginica' 'Virginica' 'Versicolor' 'Setosa'
 'Virginica' 'Versicolor' 'Versicolor' 'Virginica' 'Setosa' 'Virginica'
 'Setosa' 'Setosa']

In [60]:
# y_test 를 1차원 matrix 로 변경
y_test_flatten = np.array(y_test).flatten()

In [62]:
y_test.shape

(45, 1)

In [63]:
y_test_flatten.shape

(45,)

In [64]:
y_pred == y_test_flatten

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True])

In [65]:
print("테스트 세트의 정확도: {:.2f}".format(np.mean(y_pred == y_test_flatten))) #true와 false의 mean으로 정확도 측정

테스트 세트의 정확도: 0.98

In [66]:
print("테스트 세트의 정확도: {:.2f}".format(knn.score(X_test, y_test_flatten)))

테스트 세트의 정확도: 0.98